### ISSUE TITLE
external overlay does not pick up repo

### ISSUE THREAD

**Issue by simonschmeisser** [v4hn/ros-o-builder#12]
I tried adding a MoveIt overlay but it does not seem to use the underlaying apt repo?
https://github.com/isys-vision/ros-one-moveit-overlay

also, possibly stupid (aka lazy ...) question, do I need to sort the packages or are dependencies resolved automatically?

```
   The following packages have unmet dependencies:
   sbuild-build-depends-main-dummy : Depends: ros-one-setup-files but it is not installable
                                     Depends: ros-one-ros-environment but it is not installable
  E: Unable to correct problems, you have held broken packages.
  apt-get failed.
```

**Comment by v4hn** [comment]
Independent of your issue (which I saw just now) I fixed this error (and others) over the last two hours :)
Please have a look at the `overlay` branch.

**Comment by v4hn** [comment]
> possibly stupid (aka lazy ...) question, do I need to sort the packages or are dependencies resolved automatically?

Dependencies inside a single repos file are resolved automatically.
However, each repos file has a technical timeout of 6 hours and building the entire collected stack takes more than 12 hours from scratch.
To split huge workspaces consistently w.r.t. dependencies, I wrote a (somewhat) [small helper script](https://github.com/v4hn/ros-pkgs-split-workspace).

**Comment by v4hn** [comment]
Closing as resolved. Please post if you find further issues though, I did not test thoroughly yet.

**Comment by simonschmeisser** [comment]
Thanks! Great work!

I don't know if you fixed that as well already but I noticed that failed.md does not include the `-overlay` suffix and as such contains broken links.

**Comment by v4hn** [comment]
Yeah, that part is somewhat annoying and I ended up rewriting a lot of interfaces already. Will push something soonish. :-)

**Comment by v4hn** [comment]
It works now and the overlay specification is a bit nicer: https://github.com/v4hn/ros-o-builder/tree/overlay (https://github.com/v4hn/ros-o-builder/commit/37d8267dcd2f697a26999e08aa722e9db15c7ac2)
