### ISSUE TITLE
gtest confusion

### ISSUE THREAD

**Issue by simonschmeisser** [v4hn/ros-o-builder#14]
Most of the MoveIt and related packages in my overlay  fail due to gtest

Somehow it thinks there should be a `ros-one-gtest` package. I tried fixing that with a rosdep.yaml but that did not make a difference.

Example: https://raw.githubusercontent.com/isys-vision/ros-one-moveit-overlay/jammy-one-overlay/ros-one-opw-kinematics_0.5.0-2023.02.02.10.49_amd64-2023-02-02T10:49:11Z.build

https://github.com/Jmeyer1292/opw_kinematics/blob/master/package.xml

**Comment by simonschmeisser** [comment]
actually somehow `industrial_cmake_boilerplate` seems to create a `ros-one-gtest` target:
https://raw.githubusercontent.com/isys-vision/ros-one-moveit-overlay/jammy-one-overlay/ros-one-gtest_0.3.1-2023.02.02.10.34_amd64-2023-02-02T10:34:57Z.build

**Comment by simonschmeisser** [comment]
https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/issues/70

**Comment by simonschmeisser** [comment]
Not really an issue here

**Comment by jspricke** [comment]
You can probably add a gtest: libgtest-dev override in the rosdep.yaml

**Comment by jspricke** [comment]
never mind, seems like you tried that :D
