### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by simonschmeisser** [v4hn/ros-o-builder#15]
https://github.com/stack-of-tasks/eigenpy loads some cmake modules via a git submodule. Is there a way to resolve those?

https://raw.githubusercontent.com/isys-vision/ros-one-moveit-overlay/jammy-one-overlay/ros-one-eigenpy_2.9.2-2023.02.02.14.25_amd64-2023-02-02T14:25:56Z.build

the CMakeLists.txt tries to download it it it by itself but the build stage is offline I assume

**Comment by jspricke** [comment]
The Debian way would be to put them into an (extra) package.
