### ISSUE TITLE
Using Git LFS?

### ISSUE THREAD

**Issue by simonschmeisser** [v4hn/ros-o-builder#17]
I just had the problem that one of the debug packages was rejected for exceeding 100MB. I believe that might happen with other MoveIt packages as well.

```
##[info] Pushing
remote: error: Trace: f73fadef290104e451c1a2153e086ba22b4206e7eb5f07782a335aad1b244083        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File ros-one-eigenpy-dbgsym_2.9.2-2023.02.05.22.29_amd64.ddeb is 101.84 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./        

To https://github.com/isys-vision/ros-one-moveit-overlay.git
 ! [remote rejected] jammy-one-overlay -> jammy-one-overlay (pre-receive hook declined)

error: failed to push some refs to 'https://github.com/isys-vision/ros-one-moveit-overlay.git'
```

Would LFS files also count towards the quota?

**Comment by v4hn** [comment]
> Would LFS files also count towards the quota?

I'm not sure, but I don't think so. However, managing and especially clearing the storage would also have to be tackled.

Definitely related to #4 as we would like to sync the built files to a data drop server.
(Possibly sponsored by JSK TORKS?) :pleading_face:  @k-okada

**Comment by simonschmeisser** [comment]
I looked it up and there is a 1GB limit for both storage and bandwidth unfortunately

**Comment by v4hn** [comment]
Low bandwidth is a clear killer argument from my perspective.
