### ISSUE TITLE
Deploy process is failing  because files to remove does not exists

### ISSUE THREAD

**Issue by sugikazu75** [v4hn/ros-o-builder#23]
@v4hn 
In build-for-jammy branch, deploy action is failing because the files to remove does not exist and exit code become 1.
Merging https://github.com/v4hn/ros-deb-builder-action/pull/2 will fix problem.

**Comment by v4hn** [comment]
I don't have a lot of time at my hands the rest of this year and that missing `-f` flag is clearly required, so it fixed the problem at hand.

I would like some insights into why the debugsym packages in this builder are not generated for jammy though when the bookworm/trixie/sid builds generate them.
It's probably an error on our side, but might also be an implicit setting change somewhere between the build targets.
