### ISSUE TITLE
add moveit stack and related packages

### ISSUE THREAD

**Issue by v4hn** [v4hn/ros-o-builder#6]
I know especially I should have done that already, but I had other priorities in ROS-O for now.

**Comment by simonschmeisser** [comment]
Currently somehow the version of MoveIt (and all subpackages) is detected as 0 which makes it fail because in some cases a minimum version is required
```
ros-one-moveit-ros-planning : Conflicts: ros-one-moveit-ros-planning-interface (< 1.1.2) but 0-2023.02.09.13.48 is to be installed
```
https://github.com/isys-vision/ros-one-moveit-overlay/actions/runs/4133800349/jobs/7144142434

**Comment by jspricke** [comment]
The fork you selected is missing tags:

https://github.com/v4hn/moveit/tags

**Comment by simonschmeisser** [comment]
hmm, shouldn't the version be defined by package.xml?

**Comment by jspricke** [comment]
We use `git describe` to include the number of commits and hash to allow nightly builds with incremented version numbers:

https://github.com/jspricke/ros-deb-builder-action/blob/main/build.sh#L97

**Comment by v4hn** [comment]
The only way I see around this is, instead of relying on the git tag, to identify the latest commit that changed the package.xml's version tag and count above that one instead.

However, that is quite heavy-weight and less intuitive than simply using the latest tag. git tags with version numbers for releases are standard across FOSS git projects and even default with ROS bloom releases.

**Comment by v4hn** [comment]
done
