### ISSUE TITLE
clean integration & test of workspaces 'on top'

### ISSUE THREAD

**Issue by v4hn** [v4hn/ros-o-builder#7]
Jochen and I disagreed about how to represent that for ros-deb-builder, but I definitely want to see [my approach with a separate parameter](https://github.com/v4hn/ros-o-builder/blob/97971ac1b21ed5e9c8d1a3ef79a3e59eeac2801f/.github/workflows/build.yaml#L34-L35) working as well before we decide in a pull-request. :)
I guess there's just some details I didn't figure out last time I tried.

**Comment by v4hn** [comment]
Done. It works well as currently pushed in the `test` branch (ignoring the build failure due to my own stupidity):
```
      - uses: v4hn/ros-deb-builder-action/build@rosotest
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          ROSDEP_SOURCE: |
            rosdep.yaml
            https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one/local.yaml
          DEB_REPOSITORY: |
            deb [trusted=yes] https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one/ ./
```

I don't particularly like the fact that we have to specify almost the same url twice for debs and rosdep although both come from the same source generator.
@jspricke Any opinion on adding a separate key (e.g. `COMPACT_REPOSITORY`, `DEPDEB_REPOSITORY`, ...) to pass `https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one/` to the action only once so that the action would fill in the other two fields respectively?
Alternatively I could imagine parsing either of them to generate the other (and validate whether the entries are valid of course), but it wouldn't be very clean.
Either way I clearly prefer a separate field for `DEB_REPOSITORY` over adding sbuild flags the way you proposed.

**Comment by jspricke** [comment]
> I don't particularly like the fact that we have to specify almost the same url twice for debs and rosdep although both come from the same source generator. @jspricke Any opinion on adding a separate key (e.g. `COMPACT_REPOSITORY`, `DEPDEB_REPOSITORY`, ...) to pass `https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one/` to the action only once so that the action would fill in the other two fields respectively?

You could define it as an variable and reuse inside the yaml.

> Alternatively I could imagine parsing either of them to generate the other (and validate whether the entries are valid of course), but it wouldn't be very clean. Either way I clearly prefer a separate field for `DEB_REPOSITORY` over adding sbuild flags the way you proposed.

Can you give reason why you prefer it? Note that SBUILD_CONF will not go away as there are many more option and some, like EXTRA_REPOSITORY_KEYS can also consume the URL. So your proposal is mainly syntactic sugar leading to a less expressive interface. Given that the Action configuration is already rather short and will probably not be edited a lot, I don't see much reason to diverge to a new interface.

**Comment by v4hn** [comment]
> You could define it as an variable and reuse inside the yaml.

True, that's probably enough.

> Can you give reason why you prefer it? Note that SBUILD_CONF will not go away as there are many more option and some, like EXTRA_REPOSITORY_KEYS can also consume the URL

Paradigms of interface design. There's always a trade-off between concise statements, interface bloat, abstraction of implementation details and customizability.
Adding another deb repository is a normal use case for me (as we want people to fork and use your action on top of other such actions) and no reason to address a specific internal (sbuild) inside the action. Users don't have to understand that an action parameter will end up as an entry in an `.sbuild.rc` (instead of directly writing it to an apt sources.list entry which is not easily possible) if you can directly specify the contents. You can always argue that everyone using their own buildfarm must understand the system in detail anyway and it's not a lot of code, but that's independent of the mental load needed to parse/write the interface.

It probably makes sense to keep the `SBUILD_CONF` parameter as it is a key customization point inside the action.
Even so, the three examples you gave for using it shouldn't be there in my opinion:
1. make build verbose. verbose is the default now. If forcing quiet mode can still be done through that parameter that would be interesting use of the argument
2. adding repositories (the argument I added), see above
3. adding keys for repositories. I didn't have that use-case yet, but I clearly prefer the same approach (e.g., a `DEB_KEYS` argument) for the same reasons.


The one motivation you definitely not accept (and I see why, though I still think your proposed solution is not really good either) is that I [currently reuse the deb repositories on the host](https://github.com/v4hn/ros-deb-builder-action/blob/40a85e6684cf28184b996508ae8cb93bc80a9baf/prepare.sh#L9) to get access to `setup_files` and `ros_environment` and the syntax needed for SBUILD_CONF would just make that harder for no reason to extract it without redundant specification.

**Comment by jspricke** [comment]
> It probably makes sense to keep the `SBUILD_CONF` parameter as it is a key customization point inside the action. Even so, the three examples you gave for using it shouldn't be there in my opinion:
> 
> 1. make build verbose. verbose is the default now. If forcing quiet mode can still be done through that parameter that would be interesting use of the argument
> 2. adding repositories (the argument I added), see above
> 3. adding keys for repositories. I didn't have that use-case yet, but I clearly prefer the same approach (e.g., a `DEB_KEYS` argument) for the same reasons.

see [man sbuild.conf](https://manpages.debian.org/bullseye/sbuild/sbuild.conf.5.en.html) for a lot more options.

> The one motivation you definitely not accept (and I see why, though I still think your proposed solution is not really good either) is that I [currently reuse the deb repositories on the host](https://github.com/v4hn/ros-deb-builder-action/blob/40a85e6684cf28184b996508ae8cb93bc80a9baf/prepare.sh#L9) to get access to `setup_files` and `ros_environment` and the syntax needed for SBUILD_CONF would just make that harder for no reason to extract it without redundant specification.

I see your problem but I think reusing the same variable for different things here is rather confusing and could lead to unforeseen consequences so I would rather have that as an extra option. I'm still undecided if we should allow adding custom repos to the host system or allow setting extra variables for bloom or even clean up the package.xml files. Most of the problems in that area seem to be where people missuse the package.xml to work around rosdep so maybe it is enough to provide proper rosdep keys. Would be great if you could open an issue with the action for this use case and add some samples.

**Comment by v4hn** [comment]
> see [man sbuild.conf](https://manpages.debian.org/bullseye/sbuild/sbuild.conf.5.en.html) for a lot more options.

I explicitly asked you before what you think people will regularly use it for. These were the three use-cases you gave. ;)
I'm aware that there are many configuration options and as I said the argument should be kept to allow users to add them. But I'm also saying, that it shouldn't be necessary to specify this "advanced" argument for the envisioned regular workflows. People would just copy&paste more without understanding semantics.

> I see your problem but I think reusing the same variable for different things here is rather confusing and could lead to unforeseen consequences so I would rather have that as an extra option.

I don't want to stress this point because it's still unclear whether this is relevant once everything is cleaned up, but it is *not* different. It's exactly the same and even simpler because I just dump regular sources.list contents into a regular sources.list file. sbuild just needs the lines wrapped in syntax to log and hand them to the build env. :-)

> even clean up the package.xml files. Most of the problems in that area seem to be where people missuse the package.xml to work around rosdep so maybe it is enough to provide proper rosdep keys

The ROS-O approach I'm working on right now is to first of all use everything that is there and change only things that really need changing for newer debian systems.
Feel free to haunt OR to add correct python3 resolve values to map, e.g., `python-yaml` to `python3-yaml` on the correct target platforms. I have **no** idea why they didn't do it instead of providing separate keys.
But I will not run around and discuss with all the individual package maintainers that they should stop using the `if` attribute in their package.xmls (expect a low response rate anyway) and that it works with the debian rosdep package if you use the simpler entries. On the other side, I don't think it's helpful in any way to we fork all packages using it into ros-o to patch them there either.

**Comment by jspricke** [comment]
> I don't want to stress this point because it's still unclear whether this is relevant once everything is cleaned up, but it is _not_ different. It's exactly the same and even simpler because I just dump regular sources.list contents into a regular sources.list file. sbuild just needs the lines wrapped in syntax to log and hand them to the build env. :-)

It is not different because in your case the VM and target system are both Ubuntu 22.04, that does not generalize.

> The ROS-O approach I'm working on right now is to first of all use everything that is there and change only things that really need changing for newer debian systems. Feel free to haunt OR to add correct python3 resolve values to map, e.g., `python-yaml` to `python3-yaml` on the correct target platforms. I have **no** idea why they didn't do it instead of providing separate keys. But I will not run around and discuss with all the individual package maintainers that they should stop using the `if` attribute in their package.xmls (expect a low response rate anyway) and that it works with the debian rosdep package if you use the simpler entries. On the other side, I don't think it's helpful in any way to we fork all packages using it into ros-o to patch them there either.

As I said, I'm open to discuss different options. For using rosdep it is enough to override the keys for the build, I used the same approach before.

**Comment by v4hn** [comment]
> It is not different because in your case the VM and target system are both Ubuntu 22.04, that does not generalize.

Yes, and I concede that point. Though you conceded that it will likely work on any debian-based system we might build for. ;)
Staying with my current paradigm, the "proper" solution would be to setup an environment for the target system, ro mount the workspace and install setup_files and ros_environment in there just to sort the list of packages with `catkin_topological_order`... Which is a mess as well.

**Comment by jspricke** [comment]
> Yes, and I concede that point. Though you conceded that it will likely work on any debian-based system we might build for. ;) 

That is for your special setup_files case.

**Comment by roehling** [comment]
It looks to me that one major point of disagreement is the "interface boundary" for the user. As I understand it, Jochen considers `sbuild` the public build interface, just as it is for regular Debian packaging, and the action is just a thin wrapper. Michael considers the action itself a public interface and `sbuild` an implementation detail.

From Jochen's perspective, adding more options just adds redundancy that complicates the interface and makes the wrapper needlessly "thick". From Michael's perspective, the action is too spartantic and requires to much "fiddling" with the inner details, i.e. the sbuild implementation.

Is that about right?

**Comment by v4hn** [comment]
I believe Jochen and me were quite aware of our respective positions, as always. We have similar discussions every now and then. :grin: Thanks for spelling it out as this is a public discussion thread!

**Comment by v4hn** [comment]
[ros-o-overlay](https://github.com/v4hn/ros-o-overlay) now implements this sufficiently for my use-cases.
