### ISSUE TITLE
catkin-tools?

### ISSUE THREAD

**Issue by simonschmeisser** [v4hn/ros-o-builder#9]
Most or maybe all packages in this repo depend on `catkin` which seems to come from a PPA, maybe it would be good to copy paste it to the results "branch"?

```
 ros-one-genmsg : Depends: catkin but it is not installable
 ros-one-ros : Depends: catkin but it is not installable
 ros-one-rosbash : Depends: catkin but it is not installable
 ros-one-rosbuild : Depends: catkin but it is not installable
```
https://github.com/v4hn/ros-deb-builder-action/blob/b228fee69dc963e2544ec895f3dd7098f9179585/prepare.sh#L8

or extend the instructions in the readme.md to include the ppa?

**Comment by jspricke** [comment]
The catkin package is part of Ubuntu 22.04 and not in the PPA:
https://packages.ubuntu.com/jammy/catkin
https://launchpad.net/~v-launchpad-jochen-sprickerhof-de/+archive/ubuntu/sbuild

Maybe you forgot to enable the Ubuntu universe repo? Can you past the output of `apt update`?

**Comment by simonschmeisser** [comment]
Thanks, should have figured that out myself ...

I added
```
add-apt-repository universe
```
but it still does not find catkin.

```
Hit:1 http://apt.optonic.com/mikado/halcon bionic InRelease
Hit:2 http://apt.optonic.com/mikado/mikado-3.0 focal InRelease
Hit:3 http://ppa.launchpad.net/s-schmeisser/opt-qt-5.15.7-focal/ubuntu focal InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://packages.ros.org/ros/ubuntu focal InRelease
Ign:4 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:8 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ Release [816 B]
Ign:11 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ Release.gpg
Get:12 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ Packages [504 kB]
```
does not seem to print the enabled components. I'll debug this later myself but maybe you see something stupid ...

**Comment by jspricke** [comment]
`add-apt-repository universe` does not seem to work for me as well, maybe just add it manually:
```
sed -i 's/main/main universe/' /etc/apt/sources.list
```

**Comment by simonschmeisser** [comment]
actually `universe` is enabled already and it seems to be due to a conflict. I added `catkin` to the list of packages to be installed and get the following error:
```
Step 21/24 : RUN apt-get update && apt-get install -y --allow-unauthenticated --no-install-recommends swig catkin ros-one-ros python3-catkin-tools python3-wstool freeglut3-dev libccd-dev libglew-dev liblapack-dev python3-jinja2 codemeter libgtest-dev libogre-1.9-dev libyaml-cpp-dev libbullet-dev libnlopt-cxx-dev
 ---> Running in b27be477cad3
Hit:1 http://apt.optonic.com/mikado/halcon bionic InRelease
Hit:2 http://apt.optonic.com/mikado/mikado-3.0 focal InRelease
Hit:3 http://ppa.launchpad.net/s-schmeisser/opt-qt-5.15.7-focal/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:6 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:8 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ Release [816 B]
Ign:9 https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one ./ Release.gpg
Hit:10 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:11 http://packages.ros.org/ros/ubuntu focal InRelease
Fetched 816 B in 2s (492 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 python3-catkin-pkg : Conflicts: catkin but 0.8.10-7 is to be installed
 python3-catkin-pkg-modules : Conflicts: catkin but 0.8.10-7 is to be installed
```

**Comment by jspricke** [comment]
Drop this:
>Hit:11 http://packages.ros.org/ros/ubuntu focal InRelease

**Comment by simonschmeisser** [comment]
Thanks a lot! Now I go to the actual source of the error, I'm missing `python3-caktin-tools` for my workflow and it was pulling in the one from ros noetic repo

**Comment by jspricke** [comment]
catkin-tools is only in Ubuntu 22.10 and newer: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=catkin-tools&searchon=names

**Comment by v4hn** [comment]
> catkin-tools is only in Ubuntu 22.10 and newer

By which of course you mean "install Debian already" or just run `pip3 install catkin-tools`. :grin:

**Comment by jspricke** [comment]
..or use a newer Ubuntu or create a PPA with a backport of the Debian package (that's what I would do..)..

**Comment by simonschmeisser** [comment]
pip3 is unfortunately two releases behind but I went that way for a starter, yes.

Adding it here sounds like less work than adding a PPA? Also it keeps things in one place.  Should I open a PR?

**Comment by jspricke** [comment]
I would recommend to keep this ROS packages only (catkin-tools is a Python package) as it would make the Github Action even more complicated (thus the PPA). But not my repo.

**Comment by v4hn** [comment]
> pip3 is unfortunately two releases behind but I went that way for a starter, yes.

```
$ pip3 show catkin-tools
Name: catkin-tools
Version: 0.9.2
```
which is the current version. (it's buggy w.r.t. python3.11, but that's not relevant for 22.04) :)
So the pip installation works fine.

I agree that catkin-tools should not be packaged here. It's an external python module and this project is only about building ROS packages, not all dependencies/external tooling.

Thanks for playing around with the current state @simonschmeisser ! :-)
Notice that this is alpha/beta state right now though. I'll move the repository to ros-o once I expect it to be stable over time.

**Comment by simonschmeisser** [comment]
Interesting, https://pypi.org/project/catkin-tools/ lists 0.9.0 ...

Please let me know here or on discord or elsewhere how I can help you moving this closer from alpha to beta :wink: . If we end up using the packages from here I would snapshot them to our repository of course

**Comment by simonschmeisser** [comment]
Just for the record https://launchpad.net/~s-schmeisser/+archive/ubuntu/jammy-backports  is the PPA with backported catkin-tools
